//========================================================================================
//this is the main module. 
//there are 4 following main abstractions in the program: 
//1. GUI view - implemented with Knockout, handles GUI menu
//2. data_model - loads all the data on iniailization, 
//calculates extra data (distrance matrix) and provides data-related services to other 
//portions of the application. 
//3. map_handler - provides map-related services (show routes and points, etc.)
//4. main - controller that connects everything together. 
// Data model is accessable only by contoller. Data model has no access to contoller. 
// map handler and GUI view both can call controller methods and the other way around. 
//========================================================================================
//Data
//data is generated by a separate utility from Excel spreadheets into scripts and 
//is not supposed to be accessed by any object other than data model.
//========================================================================================
//Global variables (plan to  make them configurable too)
var MAP_INITIAL_POS = {lat: 24.4667, lng: 54.3667};
var CITY_NAME       = "ABU DHABI"

var sources_list = Array(); 
var destinations_list = Array();
var bus_route_list = Array(); 
var gui_view; 


var map_handler; 

//==========================
var UpdateMap = function(){
	var self = this; 
	self.update_map = function(){
		console.log("map was just updated");
	}
}

//============================

function initialize(){
  //populate current list with communites 
  for (var i =0; i<map_objects.length; i++){
  	//console.log(map_objects[i].class);
  	if (map_objects[i].class=="community"){
  		sources_list.push(map_objects[i]);
  	}
  	else
  	{
  		destinations_list.push(map_objects[i]);
  	}
  }

  for (var i = 0; i<bus_routes.length; i++){
  	 if (bus_route_list.indexOf(bus_routes.route)===-1){
  	 	bus_route_list.push(bus_routes.route);
  	 	//STOPPED HERE UNTESTED
  	 }
  }
  var update_map = new UpdateMap();
  gui_view = new GUIViewModel(update_map); 
  gui_view.cityName(CITY_NAME);
  gui_view.update_current_filter_list(sources_list);
  gui_view.current_step(1);
  //console.log(gui_view);

  //////////////
  

  //////////
  ko.applyBindings(gui_view);

  document.getElementById("nextStepButton").addEventListener("click", next_step);
  document.getElementById("previousStepButton").addEventListener("click", previous_step);
  

 
  this.current_step = 1;
  //ko.applyBindings(stepTitle, document.getElementById('steps'));
  /*
   
*/
}

function initMap(){
	debug_main();
	map_handler = new MapHandler(MAP_INITIAL_POS);
	map_handler.add_locations(bus_stops);

}

function previous_step(){
	if (gui_view.current_step()===2){
	  gui_view.update_current_filter_list(sources_list);
	  gui_view.current_step(1);
    }
}

function next_step(){
	if (gui_view.current_step()===1){
	  gui_view.update_current_filter_list(destinations_list);
	  gui_view.current_step(2);
    }
    console.log(local_distance_matrix);
}



(function main(){
 //debugOut(); 
  initialize(); 
})(); 

